options:
  merge-default-rules: true
  formatter: visualstudio
rules:
  indentation:
    - 1
    - size: 4
  property-sort-order:
    - 1
    - order: recess
  leading-zero:
    - 1
    - include: true
  space-around-operator: 0
